### ISSUE TITLE
Missing opening quotation mark

### ISSUE THREAD

**Issue by oliver-h** [darktable-org/luadocs#8]
https://github.com/darktable-org/luadocs/blob/78b56a695a53bdfa3b381b90f24b157df8fceb77/content/lua.scripts.manual/installation.md?plain=1#L73C4-L73C4

Ln 73 in the lua scripts installation guide is missing the opening single quotation mark. It should be 

```
    echo 'require "tools/script_manager"' > ~/.var/app/org.darktable.Darktable/config/darktable/luarc
```

Thanks for you help,
Oliver

**Comment by sercxanto** [comment]
I created a PR for it: #13 . Its a oneline change. Could someone from the team please merge it?  @wpferguson  ?
